name: Deploy Hugo Site to Google Cloud

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Hugo
        run: |
          chmod +x ./install_hugo.sh
          ./install_hugo.sh

      # run linter steps again
      # (may need to remove but no harm in having it run again)
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Pipenv
        run: python3.10 -m pip install pipenv

      - name: Install dependencies
        run: pipenv install --python=$(which python3.10)

      - name: Run linter
        run: pipenv run python lint.py

      - name: Build Hugo Site
        run: hugo

      - name: Install Google Cloud CLI
        run: sudo snap install google-cloud-cli --classic

      - name: Decode and Authenticate with GCP
        run: |
          echo "${{ secrets.GCP_CREDENTIALS_B64 }}" | base64 --decode > $HOME/gcloud-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json
        env:
          CLOUDSDK_CORE_DISABLE_PROMPTS: "1"

      - name: Remove GCP credentials
        if: always()
        run: rm -f $HOME/gcloud-key.json

      - name: Deploy to Google Cloud Storage
        run: gcloud storage rsync -r public gs://syllabus.africacode.net
